github: [your-github-username]

patreon: your-patreon-username
open_collective: your-open-collective-name
ko_fi: your-kofi-username
liberapay: your-liberapay-username
issuehunt: your-issuehunt-username
polar: your-polar-username
buy_me_a_coffee: your-buymeacoffee-username
thanks_dev: your-thanksdev-username

custom:
  - https://your-website.com/sponsor
  - https://your-company.com/support
